name: Update Gist
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
      timezone: Etc/GMT-3
permissions:
  contents: read
jobs:
  update-gist:
    name: Update Gist
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Update Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ vars.GIST_ID }}
          GIST_FILENAME: ${{ vars.GIST_FILENAME }}
        run: node updater.mjs